### PR TITLE
Support deployment pools

### LINKED ISSUE #6: [feature] Add agent in deployment mode
The image should also be capable to configure an agent in deployment mode to be used in a deployment group.

### PR DESCRIPTION
**Pull request by hangy**
Adds support for running the agent in a deployment pool instead of an agent pool.

Closes #6

### CODE REVIEW

**Comment by hangy** [comment]
I'm not 100% sure what Codacy is complaining about here. The two lists are mostly previously existing in the docs, and double quoting `$arg_pool` in this case does not work.

**Comment by kirkone** [comment]
Working on the Codacy errors

**Comment by hangy** [comment]
> Working on the Codacy errors

👍 Feel free to just squash this PR if you want to avoid too many commits to `master`. 🙂

**Comment by kirkone** [comment]
> I'm not 100% sure what Codacy is complaining about here. The two lists are mostly previously existing in the docs, and double quoting `$arg_pool` in this case does not work.

Codacy complains only at newly added code, not for existing code. 

I do not have my test environment ready at the moment. I will test this as soon as possible and finish the PR.

As you can see there ist more than a little bit to do here:
https://app.codacy.com/gh/codez-one/docker-azure-pipelines-agent/files

**Comment by hangy** [comment]
> > I'm not 100% sure what Codacy is complaining about here. The two lists are mostly previously existing in the docs, and double quoting `$arg_pool` in this case does not work.
> 
> Codacy complains only at newly added code, not for existing code.

Yup, I noticed that a bit too late.

> I do not have my test environment ready at the moment. I will test this as soon as possible and finish the PR.

I solved the `$arg..` not being quoted issue by using an array. This has the advantage of also supporting pools/deployment pools with whitespace in the name.

> As you can see there ist more than a little bit to do here:
> https://app.codacy.com/gh/codez-one/docker-azure-pipelines-agent/files

ACK. 🙂

**Pull request merged**
